### ISSUE TITLE
Yarn extremely sluggish to pan/zoom on node editor

### ISSUE THREAD

**Issue by holofoil** [thesecretlab/YarnSpinner#100]
Windows 10
Dell XPS 9560

I just downloaded Yarn, extracted the ZIP to a folder in my Documents, opened Yarn, and it's extremely sluggish to move around/zoom to the point of being unusable. Anyone else had this issue?

Is Yarn meant to be using the CPU or GPU? Wondering if that's why.

**Comment by McJones** [comment]
Hello,

The Yarn editor is a separate project from YarnSpinner, which is the tool that runs the files the Yarn editor creates. We can't fix this issue from our end, so it might be best to open an issue there: https://github.com/infiniteammoinc/Yarn/issues

sorry we can't help more with this.
