### ISSUE TITLE
Confused as to how the parsing algorithm works, and using this library

### ISSUE THREAD

**Issue by GabrielCabrera002** [thesecretlab/YarnSpinner#107]
Hello, I’ve been working on a project for a game development class, and a friend of mine suggested using YarnSpinner. I’ve thus been trying to understand how to integrate it with the project, looking at the stuff in the unity package and the c# source, but I can’t seem to understand just how the Yarn files are parsed. 

Looking through the examples just raised more questions than answers. So, could you offer some help on understanding the parsing algorithm, and making use of its output?

**Comment by McJones** [comment]
Hello, sorry I am not quite sure what you are asking for.
Are you asking about how YarnSpinner works under the hood; as in the structure of the project, the code, and how it works from a technical perspective?
Or are you after a better breakdown of how to use it in your game?
Or are you after something else?

**Comment by GabrielCabrera002** [comment]
I was asking how it worked under the hood (to get a better grasp on how to use it in my game), but after some more work, I no longer need to know (at least, for now). ^^;

**Comment by McJones** [comment]
Right-oh, I’ll close this issue for now, if you’ve got any further curiosities let us know.
