### ISSUE TITLE
What is the syntax for getting a variable value shown in text?

### ISSUE THREAD

**Issue by GabrielCabrera002** [thesecretlab/YarnSpinner#110]
I had this in a yarn node:

<<set $foodChosen to "chicken alfredo">>
The food chosen is $foodChosen. 

Displaying that with YarnSpinner, I didn't get "The food chosen is chicken alfredo.". I got "The food chosen is $foodChosen.". I assume that's because I got the syntax for putting variable values in text wrong, so I'd appreciate help with this.

**Comment by Kadelam** [comment]
Currently there is no support for expanding variables inside dialogues in YarnSpinner, see https://github.com/thesecretlab/YarnSpinner/issues/25

However the last comment in that issue provides a solution you could use in your project. https://github.com/thesecretlab/YarnSpinner/issues/25#issuecomment-227475923

**Comment by GabrielCabrera002** [comment]
Hm, that can work. Thanks :)
