### ISSUE TITLE
The either function is not a valid one?

### ISSUE THREAD

**Issue by GabrielCabrera002** [thesecretlab/YarnSpinner#112]
In Twine, either is a function that randomly returns one of the elements you pass it. For example:

either("A", "B", "C") 

returns either "A", "B", or "C" all based on its own rng. But for some reason, YarnSpinner doesn't recognize it as a valid function. I had this line in a node:

<<set $clue1 = either("SmallMirror", "TheNoid", "RonaldMcDonald")>>

And When I ran my game in Unity, an error popped up saying "either is not a valid function". I don't understand; does Yarn not have that function? What function does it have that fulfills the same purpose?

**Comment by desplesda** [comment]
Yarn Spinner doesn't define very many functions; if you want to add this, you'll need to define it yourself. Documentation on how to define your own functions is available [here](/thesecretlab/YarnSpinner/blob/master/Documentation/YarnSpinner-Programming/Extending.md).

Let me know if you need any more help! I'm closing this issue for now, but please re-open it if you need any more assistance.
