### ISSUE TITLE
Link for Slack not working

### ISSUE THREAD

**Issue by anacat** [thesecretlab/YarnSpinner#113]
When opening the narrative game dev slack link in the readme doc, the following error occurs: 
`An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.`

**Comment by desplesda** [comment]
I just tweaked the hosting settings, and it looks like it’s back up for me. 

If you can confirm that it’s back, I’ll close this issue!

**Comment by anacat** [comment]
it's working now, thank you!

**Comment by desplesda** [comment]
Awesome, thank you!
