### ISSUE TITLE
License Needed

### ISSUE THREAD

**Issue by Cypher1** [thesecretlab/YarnSpinner#115]
@desplesda recently mentioned that developers often forget to add licenses to their GitHub projects.

Is this open source? Can an appropriate license be added?

Thanks

**Comment by Kadelam** [comment]
https://github.com/thesecretlab/YarnSpinner/blob/master/LICENSE.md

**Comment by McJones** [comment]
Was fixed in commit 518ab2e1416ed3f7600c5673aa7982b326bf057e, closing for now. Please reopen if you have further issues or questions about the license.

**Comment by Cypher1** [comment]
Thanks, sorry GitHub normally recognises the license and shows it in the bar along with the commit and branch stats.

**Comment by desplesda** [comment]
I'm not sure why GitHub doesn't recognise the license file. If someone figures it out and opens a pull request that fixes it, I'll happily merge it!

**Comment by Kadelam** [comment]
It's probably because of the last paragraph.

"This software contains third-party code: Unity Test Tools (MIT license), NUnit (BSD license), NSubstitute (BSD license) and Cecil (MIT/X11 license). For more information, see the Unity Test Tools license file."

**Comment by Cypher1** [comment]
Case closed. Non standard version of the license.

Thanks for checking this out and also for the talk today. It's great to
hear about tooling and engine work.
