### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by wolfbrother9393** [thesecretlab/YarnSpinner#116]
I ran into a problem using Yarn in a WebGL build of a project. Is JSON unsupported in WebGL in general or is there something in Yarn that needs to support WebGL? What direction should I go in trying to support this?

Cheers,
-Emerson

**Comment by desplesda** [comment]
What’s the issue that you encountered?

**Comment by wolfbrother9393** [comment]
I got a long Unity box saying something about JSONs and WebGL having some sort of difficulty. Since it was for a game jam we just removed dialogue from the WebGL build. Tried to cause the same thing to happen so I could get the exact error message for you, but now I'm just getting the scene loading without any of the dialogue system associated objects showing up. Still runs in the editor and standalone.

Wasn't sure if there was some sort of known incompatibility with WebGL and JSON.

**Comment by wolfbrother9393** [comment]
I built another project using just the Yarn package stuff so I'm not sure what the deal was. I guess I'll get back to you if I encounter any problems again.

**Comment by McJones** [comment]
Right-oh, if everything is working I will close this issue.
If you run into this problem again please reopen the issue.

**Comment by wolfbrother9393** [comment]
Hey @McJones , I'm having the issue again, and this time I have the debug line that's occuring.

It reads 
Dialogue.Run was called, but no program was loaded. Stopping.

Any idea what could be causing that? The scene has been working in the past.

<img width="573" alt="screen shot 2018-02-25 at 5 48 55 pm" src="https://user-images.githubusercontent.com/9107762/36691258-ada2e9a0-1b02-11e8-8997-c34ba3076e7b.png">
