### ISSUE TITLE
ExampleDialogueUI.cs compile error (ver 0.9.3 on Unity 5.2.1f1)

### ISSUE THREAD

**Issue by empty-fortress** [thesecretlab/YarnSpinner#12]
I get this error when importing the yarnspinner package:

"Assets/Yarn Spinner/Examples/Demo Scripts/ExampleDialogueUI.cs(147,42): error CS0246: The type or namespace name `WaitUntil' could not be found. Are you missing a using directive or an assembly reference?"

I have no idea what could be causing this or how to fix it (sorry, I'm a c# and unity newbie).

**Comment by desplesda** [comment]
"WaitUntil" was added to Unity in version 5.3.2; if you can upgrade your copy of Unity, this will fix the problem. 

(Will probably remove this call to WaitUntil in the next version - there are other ways to do it that are more compatible with earlier versions of Unity.)

**Comment by desplesda** [comment]
Closing this issue for now - if you still have this problem, please reply with a comment and I'll take another look!

**Comment by empty-fortress** [comment]
The fix in your commit is perfect (there were compaints about missing NUnit but I just removed the YarnSpinnerTests file and everything works fine). Thanks a lot!

**Comment by desplesda** [comment]
:heart:
