### ISSUE TITLE
Add a variable depending on the option chosen

### ISSUE THREAD

**Issue by nicepipall** [thesecretlab/YarnSpinner#127]
Is it possible to add an int to a variable just in case if one of the answers is chosen?

For example:
![image](https://user-images.githubusercontent.com/31986672/40743651-0fcdd5fa-644a-11e8-8b76-6b03f781d9ad.png)

So in this case, I should be able to add 1 to my variable $pont just if the answer chosen is "yes". Is this possible?

**Comment by McJones** [comment]
So you can't do it all in one line as you've got there but you do it using shortcuts:
```
->Yes
    <<set $pont = $pont + 1>>
    [[Node1]]
->No
    <<set $pont = $pont + 0>>
    [[Node2]]
```

The above code should do exactly what you want and will look identical to your current Start node. I'll close this issue for now, if this isn't what you were after please reopen it.

**Comment by nicepipall** [comment]
Thank you so much McJones! It totally works!
