### ISSUE TITLE
If the Dialogue object is asked to run a node that doesn't exist, the DialogueRunner stays stuck with isDialogueRunning on.

### ISSUE THREAD

**Issue by desplesda** [thesecretlab/YarnSpinner#13]
Reported by @InfiniteAmmoInc

**Comment by desplesda** [comment]
Not able to reproduce this in 7991b902eefc3d using the attached Yarn file (note how the "Start" node links to the non-existent "Leave_" node). @InfiniteAmmoInc, do you have specific repro steps?

[Simple Example Script.json.txt](https://github.com/thesecretlab/YarnSpinner/files/138871/Simple.Example.Script.json.txt)

**Comment by InfiniteAmmoInc** [comment]
I was calling a non-existant node from StartDialogue, so maybe that makes a difference? (not sure why it would tho)

**Comment by desplesda** [comment]
Ah, there's the repro! Fix pushed in 79468ef075af2ae01468c5c4ce77720fb3cb7933. Attempting to start a run with a non-existent node will now just send an error message to `LogErrorMessage` and stop the run gracefully.
