### ISSUE TITLE
Get a yarn variable from a unity script?

### ISSUE THREAD

**Issue by foxescanfly** [thesecretlab/YarnSpinner#130]
Is there any way to access a variable set in a yarn node from a unity script (ie the dialogue UI behavior script)?

**Comment by JLevstein** [comment]
Hey @foxescanfly, I've been trying to do this myself and the way I've found to get it working is:

`VariableStoage varStore = whereverYouHaveVariableStorage.GetComponent<VariableStorage>();`

then `varStore.GetValue("$varToGet").asNumber` or `varStore.GetValue("$varToGet").asString`

Make sure to include the `$` for the variable you want to get - that tripped me up for far too long 😂

**Comment by foxescanfly** [comment]
Thanks so much for that! Have you also worked out a way to set variables from Unity in Yarn, so that (for example) a variable could be carried over multiple scenes?

**Comment by JLevstein** [comment]
@foxescanfly I have! It's in a similar pattern. Gotta be mindful that it wants a Yarn.Value, so do any calculations before you set the value.

```
var valueToSet = new Yarn.Value(valueYouWant);
varStore.SetValue("$varToSet", valueToSet);
```

**Comment by McJones** [comment]
Looks like this one is wrapped up, closing it. Feel free to open it up if you have an issue.

**Comment by guilhermehmcarvalho** [comment]
> Hey @foxescanfly, I've been trying to do this myself and the way I've found to get it working is:
> 
> `VariableStoage varStore = whereverYouHaveVariableStorage.GetComponent<VariableStorage>();`
> 
> then `varStore.GetValue("$varToGet").AsNumber` or `varStore.GetValue("$varToGet").AsString`
> 
> Make sure to include the `$` for the variable you want to get - that tripped me up for far too long 😂

Man, thank you so much! I've been trying to find out why I could set the value through a dialogue using a yarnscript but when I tried to do the same using C# it wouldn't work. If it weren't for you this would probably have taken me days!
Maybe this should be a but more explicit in the docs.

**Comment by Yulovery** [comment]
when 
`varStor.SetValue("$varToSet", valueToSet);`    a consel report Object reference not set to an instance. varStor is an object, value to set is defined. It cant find the variable in Yarn for some reason. $varToSet is defined in the yarn program, i think. 

p.s. Is there a way to create a vairable in yarn scripts without setting a value?
