### ISSUE TITLE
Get VariableStorage Variable by Index

### ISSUE THREAD

**Issue by netherchef** [thesecretlab/YarnSpinner#133]
Hey guys and gals, I can't seem to get a variable from the Variable Storage by its index?

![image](https://user-images.githubusercontent.com/36320370/43884737-7bf69312-9be9-11e8-87bf-8f14d5cec1f6.png)

**Comment by james-sullivan** [comment]
Aren't the variables stored in a dictionary where the keys are strings? They don't have integer indexs.

**Comment by McJones** [comment]
As was mentioned, variables are indexed by their name not as integer.
There is already a built in function in the variable storage for getting variables back out, GetValue().

So you'd use it something like:
````
string value = variableStorageScript.GetValue("$variableName").AsString;
````
