### ISSUE TITLE
Saving Yarn variables for use in other scenes (Unity)

### ISSUE THREAD

**Issue by Sazazezer** [thesecretlab/YarnSpinner#140]
Is there anything already in place, when using YarnSpinner in Unity, to save a variable used by YarnSpinner to be used in dialogue in another scene (or even the same scene when reentering the room at a later date). For example, Player enters scene 1, speaks to Sally, who asks them to get something in scene 2 (setting variable fetchQuest from 0 to 1). Player goes to scene 2, gets item (setting variable gotItem from 0 to 1), and returns to scene 1. Player then speaks to Sally, who now speaks a line of dialogue that will only happen if both variables are set to 1.

I can do all this fine if everything happens in the same scene, but not in different scenes, since everything resets when you reenter the scene.

I'm thinking i would need to use serialization to save the variable into a json script, and then reload that json script when the player character renters the scene. The issue i'm having with this though is getting the Yarn variable to be altered by any outside source. I could make a Yarn action to change variables outside of Yarnspinner, but i'm not sure how to get Yarnspinner to read those changes at the start of a scene, since a Yarnspinner dialogue needs to run before it changes any Yarn variables, and the Yarn variable will need to be changed before the dialogue starts.

Hope all that makes sense. Thanks in advance.

**Comment by Subliminalman** [comment]
The way I get around this is by making my VariableStorage object not destroy on load between scenes. I use it in a Singleton type pattern where I only have one VariableStorage and it stays loaded for the duration of the game which can then save and load game files.

Here's the relevant Unity doc https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

**Comment by Sazazezer** [comment]
Thanks for this. I implemented a singleton pattern and was able to get the script to persist between rooms.

If i may ask a follow up question on the same subject, what method should i be using to save/serialize the Dialogue VariableStorage between playthroughs?  `[[System.Serializable]]` doesn't accept Dictionary entries so i can't save `Dictionary<string, Yarn.Value> variables` to a json file.

**Comment by fragmental** [comment]
@Sazazezer did you solve this?  This might be useful, https://stackoverflow.com/questions/5597349/how-do-i-convert-a-dictionary-to-a-json-string-in-c.  I was looking at the save implementation in the save branch and it uses Newtonsoft.Json and Newtonsoft.Json.Linq.  I'm not entirely sure what it's doing, though.

What were you using for JSON in Unity?  JsonUtility?  I've done a bunch of stuff with JSON in Unity, but as far as I can recall, I haven't actually tried to serialize a Dictionary (I could have just forgotten, though), or I would have more specifically useful suggestions.  I work with Lists more often.

**Comment by Subliminalman** [comment]
So I haven't come around to this yet but something you can do is create a Serializeable class that holds a string and a Yarn value and have a List of those to save those out to your JSON.

Here's the gist of what you can do. Didn't add in the JSON serialization cause I don't know what library you want to use.

```C#
Dictionary <string, Yarn.Value> values;

void Save () {
  List<YarnKeyValue> ykv = new List<YarnKeyValue>();

  foreach (val v in values) {
    ykv.Add(new YarnKeyValue(v.Key, v.Value));
  }

  //Save to JSON here
}

void Read (List<YarnKeyValue> _fromJson) {
  foreach(var v in _fromJson) {
    values.Add(v.key, v.value);
  }
}

[Serializable]
class YarnKeyValue {
  public string key;
  public Yarn.Value value;
 void YarnKeyValue(string _key, Yarn.Value _value) {
    key=_key;
    value=_value;
  }
}
```

**Comment by Sazazezer** [comment]
@fragmental Sorry for the late reply. I moved on to something else and i'm just coming back to this now. I'm using JsonUtility. It seems to be the general consensus looking around stackoverflow that dictionaries can't be serialized without special assets. I've been following @Subliminalman suggestions for converting the dictionary to a list. It's mostly working now but i'm trying to iron out a few bugs (the json output comes out as [{"key":"$Yarn.ShuffleOptions"},{"key":"$variableName"}] and similar. I'll play with it a bit more and see if i can sort it out. Thank you both for your help.

**Comment by Sazazezer** [comment]
@Subliminalman 
Was the 'void YarnKeyValue()' here supposed to be a method or a constructor?

`[Serializable]
class YarnKeyValue {
  public string key;
  public Yarn.Value value;
 void YarnKeyValue(string _key, Yarn.Value _value) {
    key=_key;
    value=_value;
  }
}`

If i keep it as a method, it brings up a 'member names cannot be the same as their enclosing type' error. If i turn it into a public constructor it outputs [{"key":"$Yarn.ShuffleOptions"}] as opposed to something like [{"$Yarn.ShuffleOptions":"1"}] (i.e. v.Key + v.Value).

Thanks again.

**Comment by Subliminalman** [comment]
Are you talking about when you call it in a string? If so you can change it to this.
(also fixed it to be a constructor, sorry about that)

```
[Serializable]
class YarnKeyValue {
  public string key;
  public Yarn.Value value;
  public YarnKeyValue(string _key, Yarn.Value _value) {
    key=_key;
    value=_value;
  }
  public override ToString () {
    return "" + key + ":" + value.ToString();
  }
}
```

Not sure if that's what you're looking for.

**Comment by Sazazezer** [comment]
Thanks. I'm not trying to call it in a string, but it looks like it ends up outputting to the json file the "key" part somehow (i don't need "key" to show up at all). The `dialogueList.Add(new YarnKeyValue(v.Key, v.Value));` part seems to result in `"dialogue":[{"key":"$Yarn.ShuffleOptions"}]}`, when it should be resulting in `[{[$Yarn.ShuffleOptions, [Value: type=Bool, AsNumber=0, AsBool=False, AsString=False]]` (i.e. the Yarn variable's name and value).

Here's my version of the code below (minus the Read function as i haven't gotten to loading stuff yet):
````
  [Serializable]
  public class YarnKeyValue{
      public string key;
      public Yarn.Value value;

      public YarnKeyValue(string _key, Yarn.Value _value) {
          key=_key;
          value=_value;
      }
    }
    public void Save(){
        List<YarnKeyValue> dialogueList = new List<YarnKeyValue>();

       foreach (var v in GameObject.FindObjectOfType<DialogueStorage>().variables){
           dialogueList.Add(new YarnKeyValue(v.Key, v.Value));
       }       

          data = new SaveData() { 
              dialogue = dialogueList //sends it to the SaveData class dialogue variable
          };
         //Extra ToJson stuff goes here for writing to the output file
    }
````

If i run Debug.Log on the v.Key and v.Value while the Save function is running, it shows the correct outputs, `(v.Key = $Yarn.ShuffleOptions, v.Value = [Value: type=Bool, AsNumber=0, AsBool=False, AsString=False]`), but when `dialogueList.Add(new YarnKeyValue(v.Key, v.Value));` is ran it seems to see v.Key as the name of the key variable in the YarnKeyValue class ("key") and v.Value as the name of the Yarn key within the DialogueStorage class (" $Yarn.ShuffleOptions"), which is very confusing as it looks like it's somehow mixing up the variables even after the Debug.Log has just confirmed them.

**Comment by Subliminalman** [comment]
Ok so I wrote out a simple version that works. There's 1 new file SaveTest.cs, and 2 modified files ExampleVariableStorage.cs and Value.cs

Let's first start with the SaveTest.cs 
I'm using Newtonsoft Json serialization since I know it best and I can never seem to get the Unity JsonUtility to work for me.

I removed the YarnKeyValue and replaced it with a class called YarnSaveState. This holds 2 dictionaries, the variables <string, Yarn.Value> dictionary from ExampleVariableStorage.cs and the visitedNodes<string,int> dictionary from Dialogue.cs

This simplifies what we need to keep track of and now we don't have to convert dictionaries over.

SaveTest.cs
```C#
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Yarn;
using Yarn.Unity;

public class SaveTest : MonoBehaviour {
	public ExampleVariableStorage variableStorage;
	public DialogueRunner dialogueRunner;
	public string externalJson = "";

	void Update () {
		if (Input.GetKeyDown(KeyCode.K)) {
			Save();
		}
		if (Input.GetKeyDown(KeyCode.L)) {
			LoadFromJson();
		}
	}
	
	void Save () {
		YarnSaveState yss = new YarnSaveState(variableStorage.Variables, dialogueRunner.dialogue.visitedNodeCount);
		//Save to JSON here
		string json = Newtonsoft.Json.JsonConvert.SerializeObject(yss);
		Debug.Log(json);
	}
		
	void LoadFromJson () {		
		YarnSaveState yss = Newtonsoft.Json.JsonConvert.DeserializeObject<YarnSaveState>(externalJson);
		foreach(var v in yss.values) {
			variableStorage.SetValue(v.Key, v.Value);
		}

		dialogueRunner.dialogue.visitedNodeCount = yss.visitedNodes;
	}
		

	class YarnSaveState {
		public Dictionary<string, Yarn.Value> values;
		public Dictionary<string, int> visitedNodes;
		public YarnSaveState (Dictionary<string, Yarn.Value> _values, Dictionary<string, int> _visitedNodes) {
			values = _values;
			visitedNodes = _visitedNodes;
		}
	}
}

```

Next is ExampleVariableStorage.cs

The only thing I modified here was adding this line. This is so we can access and serialize this variable. You can also make variables public but I decided to do it this way instead.

```C#
public Dictionary<string, Yarn.Value> Variables {
		get { return variables; }
}
```

And finally is Value.cs
I wanted to try not to mess with core YarnSpinner code as much as possible.
Here we just set the variables to be serialized.

```C#
[Newtonsoft.Json.JsonObject(Newtonsoft.Json.MemberSerialization.OptIn)]
    public class Value : IComparable, IComparable<Value> {
        public static readonly Value NULL = new Value();

        public enum Type {
            Number,  // a constant number
            String,  // a string
            Bool,    // a boolean value
            Variable, // the name of a variable; will be expanded at runtime
            Null,    // the null value
        }

        public Value.Type type { get; internal set; }

        // The underlying values for this object

		[Newtonsoft.Json.JsonProperty]
        internal float numberValue {get; private set;}
		[Newtonsoft.Json.JsonProperty]
        internal string variableName {get; set;}
		[Newtonsoft.Json.JsonProperty]
        internal string stringValue {get; private set;}
		[Newtonsoft.Json.JsonProperty]
        internal bool boolValue {get; private set;}

...
```

Put SaveTest.cs onto a game object and place your variable storage as a reference to it. You can load a json string through the inspector to load, or you can access it via a file (didn't write it for testing though).

I've attached my working files so you can look through them, let me know if that works out for you.

Cheers!

[Uploading YarnSaving.zip…]()

**Comment by Sazazezer** [comment]
Oh wow. That's amazing. Thanks for your time. I've implemented the new class and put my json stuff in it, and it looks like it's now all mostly working. I can run Save and LoadFromJson and it saves and loads the variable storage into Unity as expected.

Only issue i had was with Value.cs and serialising the types. Since i'm using `using Yarn.Unity` i don't have a folder with this class in in my Unity build. How should  i go about editing/adding this? I tried just adding the Value.cs from [the YarnSpinner folder](https://github.com/thesecretlab/YarnSpinner/tree/master/YarnSpinner) and then adding your changes but other files in my build started throwing up interface errors so i didn't want to go down that route unless i was certain it was the right way to do it.

**Comment by Sazazezer** [comment]
Thanks, but i'm not sure it is working correctly. For an example when the Save function is ran the Json output is returning `"$go_get_rock":{"type":2,"AsNumber":1.0,"AsBool":true,"AsString":"True"},`, but when the  LoadFromJson function is ran it seems to load fine but shows no sign of loading the dialogue variables, and a Debug.Log of the variable storage shows up as `$go_get_rock = [Value: type=Null, AsNumber=0, AsBool=False, AsString=null]`.

I think i do need to serialize those variables.

**Comment by ChubbyPitbull** [comment]
Hey, just chiming in, I got this to mostly work but was having the same problem as @Sazazezer where the values were coming up as null. I was using @Subliminalman 's code and serializing worked correctly but the deserializing was producing the null values. Once I added "[Newtonsoft.Json.JsonProperty]" above "public Value.Type type { get; internal set; }," the type was now being included in the save file and I was able to deserialize everything correctly.

**Comment by Sazazezer** [comment]
Aw man. I spent half of Friday basically writing a huge workaround to get around this and finally got it working using the extending Yarnspinner style functions. Went back to an old commit to try your suggestion and it worked straightaway! I chose a far too complex route to sort this out...

Thanks for the input. It's helped a lot.

**Comment by McJones** [comment]
This looks like it is wrapped up, closing, feel free to open it back up if there are related issues.

**Comment by Shrubhog** [comment]
I hate to necro an issue, but how exactly was this solved? I've been banging my head against the wall with that null deserialization bug, and I can't override the Value class.

**Comment by desplesda** [comment]
This discussion is now pretty out of date, since it's referring to the use of Newtonsoft.Json types (which were removed in v0.9.12). Can you open a new issue and report the problem you're seeing?

**Comment by Shrubhog** [comment]
Well, actually, that makes a great deal of sense. I'll move to a more
recent serialization method and see if it works. Thanks.
