### ISSUE TITLE
Check a non-yarn variable within a yarn script (Unity)

### ISSUE THREAD

**Issue by Sazazezer** [thesecretlab/YarnSpinner#147]
Is there a standard way to access a non-yarn variable within a Yarn script? For example, to check the state of a game object and have that determine the conversation.

I'm thinking something like:
````
    [YarnCommand("checkLock")]
        public bool CheckLock(string objectToCheck) {
            GameObject lockedItem = GameObject.Find(objectToCheck);
            if( lockedItem.GetComponent<Lockstatus>().locked == true){
                return true;
            } else {
                return false;
            }
        })
````
````
title: TestScript
---
<<if checkLock TestScript LockedChest is true>>
The chest is locked.
<<endif>>

<<if checkLock TestScript LockedChest is false>>
The chest has now been unlocked. It's empty!
<<endif>>
````

**Comment by Subliminalman** [comment]
Look into creating a custom command.  Pretty much the same kind of pattern but it will return a value to you.

This is how they created the visited("NODE NAME") command in yarn.

[Extending Commands](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/YarnSpinner-Programming/Extending.md)

**Comment by Sazazezer** [comment]
Thanks a lot. That wasn't as hard as it first started to look.

For future curious people. Final code ended as below:

````
<<if check_lock("LockedSideboard")>>
The chest is Locked.
<<else>>
The chest is open
<<endif>>
````
Registered Function (i dumped this in the void Start of DialogueRunner)
````
            dialogue.library.RegisterFunction ("check_lock", 1, delegate(Value[] parameters) {
                Debug.Log((string)parameters[0].AsString);
                Debug.Log(GameObject.Find((string)parameters[0].AsString));
                return GameObject.Find((string)parameters[0].AsString).GetComponent<TreeBurn>().locked;
````

**Comment by McJones** [comment]
Glad this got resolved, closing.
