### ISSUE TITLE
Improve Documentation On Node Headers And Extended Commands

### ISSUE THREAD

**Issue by tomdominer** [thesecretlab/YarnSpinner#149]
At the moment, there are a few behaviours in Yarn files interpreted by YarnSpinner which the documentation fails to mention.

Firstly, you cannon use the colon ":" or space " " character in node headers. (Full stops as dividers are supported though.) Maybe mention this in the "Yarn Quick Reference" node section of the documentation.

Secondly, you can use either parentheses and comma **custom_command(1.0, true)**, or just spaces **custom_command 1.0 true** when sending extended commands parameters back to Unity. Perhaps include example command calls in the "Extending Yarn Spinner" section.

**Comment by PeteLawler** [comment]
Hi Tom, apologies for the lengthy delay in responding to you. Whilst I'm not part of the development team, and don't know where they plan on taking things nor where things are now in relation to your request, I'd encourage you to create a pull request that may be able to be merged. Meanwhile, @desplesda may be able to give some insight though I understand he's currently pretty busy with iOS porting of things.

**Comment by TheMartianLife** [comment]
Thanks for reaching out! Discussion moved to #168, where I have pulled it in with a few related issues to discuss disallowed symbols in the future. Please let us know your thoughts there :)
