### ISSUE TITLE
Should Value.CompareTo() use AsNumber instead of AsString as a fallback when types don't match?

### ISSUE THREAD

**Issue by adamgryu** [thesecretlab/YarnSpinner#151]
Today I noticed some unexpected behaviour. I used an expression like this:
`<<if $undefinedvariable <= 2 >>`
I was surprised to find $undefinedvariable (which was currently Value.Null) was considered larger than 2.

When I looked inside the Value class, I noticed that CompareTo() uses this line to compare values when the types don't match:
`// try to do a string test at that point!`
`return this.AsString.CompareTo(other.AsString);`

What do you think about changing it to use AsNumber instead? This would give behaviour more similar to javascript, so you can compare things like:
`false < 2     -> true`
`false > 0     -> true`
`null < 0     -> false`
`null < 1     -> true`

**Comment by McJones** [comment]
This is a really good question to ask, I'm not really sure is the answer.
Personally I like the idea of $undefinedvariable always evaluating to false when compared unless you compare it to Value.Null directly.

Do people think that using JS as the comparison model is the right way to go or should we special case null?

**Comment by TheMartianLife** [comment]
Great question! Rolled in with others in #167 to discuss the behaviours any changes may incur. We'd love to hear your thoughts there!
