### ISSUE TITLE
float.Parse() fails sometimes when the computer language isn't English

### ISSUE THREAD

**Issue by adamgryu** [thesecretlab/YarnSpinner#154]
In Parser.cs line, 861:

`value = new Value(float.Parse(t.value as String));`

When a playtester tried my game on a computer with a French Canadian keyboard, the dialogue would crash.

I think it needs to be changed to this:
`value = new Value(float.Parse(t.value as String, System.Globalization.CultureInfo.InvariantCulture));`

**Comment by Tamschi** [comment]
I'll try my hand at this. There's a lot of places where `CultureInfo` isn't specified, so I think it makes sense to configure a warning for it and clear all of them at once.
