### ISSUE TITLE
NULL Values should have actual underlying values

### ISSUE THREAD

**Issue by mutmedia** [thesecretlab/YarnSpinner#157]
Is there any specific reason why NULL values dont have 0, "" and false as it's underlying values?

It feels inconsistent being able to do some comparison operations (equality), and not others (greater than)

**Comment by McJones** [comment]
Related to issue #151 do people think we should be special casing null.
My gut feeling is we should be handling that as a special case as it does work slightly differently.

What do other people think.

**Comment by TheMartianLife** [comment]
Agree with @McJones. Making NULL == 0 or anything else makes for bizarre behaviour where you get things like a) making something equatable makes it comparable, so you can get things like NULL > -1 would be true and b) for some of the ways different types are inferred when passed from Yarn to C# or Unity, it could even potentially see NULL values change type in different contexts or after checking?

Seems like a general bad idea. However, should probably join #151 in a discussion on either tweaking comparisons or officiating a type system.
