### ISSUE TITLE
Website: "Learn about ...." links are broken

### ISSUE THREAD

**Issue by BillyWM** [thesecretlab/YarnSpinner#158]
You've moved files around in the repo but haven't updated the links. 3/4 are broken.

> ~~Learn how to build Yarn Spinner from source.~~
> Learn more about Yarn, and the Yarn editor.
> ~~Learn more about writing dialogue in Yarn.~~
> ~~Learn about using Yarn Spinner in your Unity game.~~

**Comment by PeteLawler** [comment]
Many apologies for the delayed reply. Are you talking about the first four dot points from 'What To Do Next' on https://github.com/thesecretlab/YarnSpinner/blob/master/README.md ? I've just tested them and they seem to be currently working. If you could clarify it'd be greatly appreciated. Once again, my apologies for the delay.

**Comment by james-sullivan** [comment]
I think he might be referring to the learn links on your website.
https://www.secretlab.com.au/yarnspinner

**Comment by BillyWM** [comment]
@PeteLawler: No worries. Just mentioning small errors I happen to notice as I pass through.

@james-sullivan: Yes that's correct.

**Comment by PeteLawler** [comment]
Ah right, that is a page owned by Secret Lab, the creator of and major contributor to the project but owned by that company and not generated by this project. As such, I'm going to ping @desplesda and @parisba about it, as they own that company. However, as it's not anything specific to this project or able to be edited by this project, this is an invalid bug. I encourage you to contact Secret Lab via https://www.secretlab.com.au/contact-rally  if they do not respond to my ping here.

**Comment by parisba** [comment]
Fixed 😍
