### ISSUE TITLE
Inserting the "#" character and print it

### ISSUE THREAD

**Issue by TheSomeoneXD** [thesecretlab/YarnSpinner#160]
I've been using TextMesh Pro in Unity, and I was trying to put hexadecimal values in tags like this:

`<#BFDCE1>Boy:</color> When are we getting out? I don't like it here. I wanna go home...`

The problem here is the hashtag. In the Yarn editor, it turns all the text after it grey, and I can't escape it with \\#. If I tried to run that line in YarnSpinner, it wouldn't work.

Any idea of what the hashtag even does? And how can I get YarnSpinner to simply print out the character? Thank you.

**Comment by desplesda** [comment]
Hashtags are used by Yarn Spinner to add additional information about a line, like its unique line code (which games can use for doing localisation or voiceovers.)

As a workaround, you could replace the # with any other symbol, and in the code that receives the line string, swap it back to a # before providing it to TextMeshPro.

**Comment by TheSomeoneXD** [comment]
Thank you so much! Got your workaround to work perfectly.
