### ISSUE TITLE
Title with space

### ISSUE THREAD

**Issue by schallerala** [thesecretlab/YarnSpinner#162]
If a title includes a space and we want to create a link to it, the following element will fail parsing.

I have a story that has a _standard_: '_previous_', '_next_' options at the end of a passage. The _previous_ link referring my first passage that contains a space in his title. The second option will fail parsing.

**Comment by McJones** [comment]
If I’m understanding you correctly you’ve got a story passage that is named something like “node name” (ignoring the quotation marks) and then you are trying to link to with something like [[previous|node name]]?
If that’s the case then that is an error, story nodes can’t have spaces, : or # in them (might be a few more restricted characters but those are the main ones I remember off the top of my head).

Is that the case? If so you (or I can) close the issue.
If that isn’t the case can you post some snippets of your yarn files that have this issue so we can take a closer look.

**Comment by TheMartianLife** [comment]
Thanks for reaching out! Discussion moved to #168, where I have pulled it in with a few related issues to discuss disallowed symbols in the future. Please let us know your thoughts there :)

**Comment by schallerala** [comment]
@McJones yes, that is the case. 
As I could do it with _Twine_ and its different story player, I taught you could do it too with Yarn.

But as @TheMartianLife said, its great that it will be added in the documentation to let others know about those restrictions.
