### ISSUE TITLE
Bad pattern for 2+ digit decimal numbers

### ISSUE THREAD

**Issue by rakkar1974** [thesecretlab/YarnSpinner#169]
This will fail to parse 0.25 but will work with 0.2

<<if 0.1 < 0.25 >>
	1
<<else>>
	2
<<endif>>

Reason:
Pattern is wrong in Lexer.cs:
patterns[TokenType.Number] = @"\-?[0-9]+(\.[0-9+])?";

Should be:
patterns[TokenType.Number] = @"\-?[0-9]+(\.[0-9]+)?";

**Comment by TheMartianLife** [comment]
We'll look into it. This might explain #148 also. Thanks for letting us know!

**Comment by TheMartianLife** [comment]
Closing this as the request was merged. Feel free to open again if you have any other issues!
