### ISSUE TITLE
Bug with parsing commands

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#20]
Looks like the command "toggleBlinks" is throwing an error
"Expected a statement here but got BeginCommand (<<) instead (was there an unbalanced if statement earlier?)"

It doesn't compile with the text toggle, toggl, togg, tog, to but does compile with just: t. So I'm guessing maybe it's the word "to" that is throwing it off?

**Comment by desplesda** [comment]
Fixed by making the parser realise that the “to” token actually means “the letters T and O followed by NO OTHER LETTERS PLS"

**Comment by desplesda** [comment]
(The test case also includes words with other keyword-like prefixes, like “nulled”, “orion”, “andorian”, “settings”, so those should now work too.)
