### ISSUE TITLE
VariableStorage does not exsist in Yarn namespace

### ISSUE THREAD

**Issue by marcr91** [thesecretlab/YarnSpinner#26]
After the first time opening the Unity project I immediately get this error ;

"Assets/Yarn Spinner/Code/DialogueRunner.cs(230,78): error CS0234: The type or namespace name `VariableStorage' does not exist in the namespace `Yarn'. Are you missing an assembly reference?"

Am I missing a script somewhere with this namespace?
Using Unity version 5.3.2.

**Comment by desplesda** [comment]
It sounds like you've checked out the code from Git, but the compiled Yarn Spinner DLL (which isn't included in the Git repo) is missing.

To fix this, download the latest release's unitypackage (https://github.com/thesecretlab/YarnSpinner/releases), and open it. Click Import, and your problem should be fixed!

**Comment by marcr91** [comment]
That fixed it. Thanks so much!!

**Comment by desplesda** [comment]
Awesome! Let me know if you have any more issues.
