### ISSUE TITLE
Parse Exception Error Message Update

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#27]
ParseException: Line 27:0: Expected a statement here but got Dedent instead (was there an unbalanced if statement earlier?)

^ would it be possible to get this to display the name of the node where the parse exception occurred? 

That'd be a big help in tracking down these types of errors. :) (right now I'm getting one of these in a massive file)

**Comment by desplesda** [comment]
Ok, try out the DLL in this package. It should report errors a little better. If it works out, I'll merge it into master.

[YarnSpinner-0.9.6-8-g01cfae5.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/149689/YarnSpinner-0.9.6-8-g01cfae5.unitypackage.zip)

**Comment by desplesda** [comment]
(The DialogueRunner.cs file has also been updated, so import that too!)

**Comment by InfiniteAmmoInc** [comment]
Cool! That seems to work. :) 

This code seems to fail on line 27. I'm not really seeing why? Could be a parser error or I could be missing something obvious. :P 

`<<if $mom > 0>>
    <<if $mom_church is 0>>
        Mom: How's the headache?
        Mae: Still there. Being out and about helps.
        Mom: I bet!
        <<set $mom_church += 1>>
    <<elseif $mom_church is 1>>
        Mom: Thanks for visiting me here, btw.
        Mom: I like seeing you! It brightens my day!
        Mae: Feels weird being here today.
        Mae: Like... there's so much empty space.
        Mom: Come on sunday! It's full then!
        Mae: I bet it is!
        <<if $money_trouble is 1>>
        	Mae: sorry you have to work b/c money problems
        	Mom: mae I've always had a job
        	Mom: this is just another one
        <<endif>>
        <<set $mom_church += 1>>
    <<elseif $mom_church is 2>>
        [[MomChurch_A3D3_Loop]]
    <<endif>>
<<else>>
     <<if $mom_church is 0>>
        <<set $mom_church += 1>>
        [[MomHome_A3D3_00]]
    <<elseif $mom_church is 1>>
        <<set $mom_church += 1>>
        [[MomHome_A3D3_01]]
    <<elseif $mom_church is 2>>
        [[MomChurch_A3D3_Loop]]
    <<endif>>
<<endif>>`

**Comment by desplesda** [comment]
Weird. I ran that through the latest parser, and it worked fine. I also [double-checked the if-else-end balancing](https://github.com/thesecretlab/YarnSpinner/files/149727/mom-rebalanced.txt), and it also seemed fine.

Hmm.

**Comment by InfiniteAmmoInc** [comment]
Yeah, weird still get 'ParseException: In file <input>: Error parsing node MomChurch_A3D3: Line 27:0: Expected a statement here but got Dedent instead (was there an unbalanced if statement earlier?)'

Maybe I'll try copy-pasting the rebalanced code O.o

**Comment by desplesda** [comment]
Summarising a conversation I had with @InfiniteAmmoInc: This turned out to be because an `if` statement was one space further indented than its `endif`, causing the parser to get confused about why there was a `Dedent` token when it expected an `EndIf` token.

Fixed in 52a3ae392d by making if statements ignore any `Dedent` tokens before their `<<else>>`, `<<else if` and `<<endif>>`.

**Comment by desplesda** [comment]
Wait, this particular bug is not yet fixed. Will re-open and continue looking.

**Comment by desplesda** [comment]
Alrighty, try this one.

[YarnSpinner-0.9.7-5-ge2f1cfb-source-minimal.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/149895/YarnSpinner-0.9.7-5-ge2f1cfb-source-minimal.unitypackage.zip)

**Comment by desplesda** [comment]
This hopefully fixes the issue by making the lexer only track indentations that occur either on the line that contains a `->`, or on the line following. Dedents are only tracked if they cross the threshold established by a previously tracked indent. Whew.

**Comment by desplesda** [comment]
Now properly fixed in [v0.9.7.2](https://github.com/thesecretlab/YarnSpinner/releases/tag/v0.9.7.2).
