### ISSUE TITLE
Dialogue.Stop() sometimes has null VM

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#29]
Wondering if It'd be alright to add a null check for the vm in Dialogue.Stop() (Dialogue.cs line 245)

Just seeing it error log a null there sometimes.

**Comment by desplesda** [comment]
Makes sense to add a check like that. The only time I think that could happen is if the dialogue is unloaded before Stop is called; are you seeing it happen at other times?

**Comment by InfiniteAmmoInc** [comment]
Not sure why it's happening yet, might investigate further...

**Comment by desplesda** [comment]
Actually, reading the code, the VM is never set to null. The only time it can be null is after you create the Dialogue, but before you call Run.

Anyway, adding a check, because it’s sensible to do so!

**Comment by desplesda** [comment]
Package attached!

[YarnSpinner-0.9.7.2-2-g02a69ab-development-source-minimal.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/153589/YarnSpinner-0.9.7.2-2-g02a69ab-development-source-minimal.unitypackage.zip)
