### ISSUE TITLE
Support for floating point (decimal point?) numbers

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [thesecretlab/YarnSpinner#33]
Not sure if the parser knows how to handle this yet. It seems to compile fine with $player_y > -1 but not $player_y > -1.45

```
<<if $player_y > -1.45>>
    <<playerFallThrough wait>>
<<endif>>
```

**Comment by InfiniteAmmoInc** [comment]
Interesting temporary work around to this: <<if $player_y * 10 > -14>> :)

**Comment by desplesda** [comment]
Haha! Yeah, that'll work. But I'll add proper floating-point support, too.

**Comment by desplesda** [comment]
This will come about partially as a result of #38.

**Comment by desplesda** [comment]
This is now done, as at b9908eb76, and it will be in the next release.
