### ISSUE TITLE
Interest in expanding VariableStorage interface?

### ISSUE THREAD

**Issue by konistehrad** [thesecretlab/YarnSpinner#35]
Is there interest in expanding the Yarn.VariableStorage interface to accept more datatypes? In particular, some of the legacy Twine code I'd be interested in porting would require allowing storage of strings, which is supported by Twine but not currently Yarn.VariableStorage. There's also the matter of Arrays to contend with but let's take it one step at a time if there's interest in expanding this functionality.

Thanks for this excellent package, BTW!

**Comment by ikofarlight** [comment]
I know there was some discussion of expanding variable storage to handle values beyond just numbers over on another issue #25

**Comment by konistehrad** [comment]
Yikes my apologies closing as a duplicate!

**Comment by desplesda** [comment]
👍

This is something that I'd like to see added sooner rather than later, because it'll be needed for localization as well as being super useful on its own.
