### ISSUE TITLE
Allow storing additional types in variables

### ISSUE THREAD

**Issue by desplesda** [thesecretlab/YarnSpinner#36]
Currently, variables can only store numbers. This is a limitation of `VariableStorage`, not of the language - while `Value`s are capable of storing any type currently known to the language, there's simply no way for clients to store any type besides numbers in variables.

To address this, `VariableStorage` should be extended to allow either storing `Value`s directly, or have per-type methods (e.g. `SetString`, `SetNumber`, `SetBool` etc)

**Comment by konistehrad** [comment]
As promised, I have a branch up here: https://github.com/konistehrad/YarnSpinner/tree/36-value-backed-storage

I have isolated a minimum test case that's working in Twine but failing in Yarn that I haven't yet isolated. In particular, I'm working on how to get the test harness to better signal the failing line. If you have a couple minutes, I would love some feedback.

Note: I ended up going with overloaded operators for Value operations, which I generally don't prefer, but calling `.Add` and `.Subtract` for every possible operation got really tedious, and ended up looking better both in `Value.cs` and its consuming code. I can refactor that out pretty easily if you want to avoid that structure.

**Comment by desplesda** [comment]
If you open a pull request, I can look at all of the commits at once!

(Also: OMG NICE)

**Comment by konistehrad** [comment]
@desplesda didn't want to open a PR prematurely (it is still busted 😉), but here it is! https://github.com/thesecretlab/YarnSpinner/pull/37

**Comment by konistehrad** [comment]
Oh right, one more note: in an attempt to preserve Twine compatibility, I've been striving to keep JS variable semantics alive in a lot of this as opposed to C#. Adding `null` and `"test"` for example will yield `"nulltest"` (JS semantics) as opposed to `"test"` (C# semantics).

**Comment by desplesda** [comment]
Done, thanks to @konistehrad's work in #37.
