### ISSUE TITLE
Replace current lexer with a state machine

### ISSUE THREAD

**Issue by desplesda** [thesecretlab/YarnSpinner#38]
The lexer (see Tokenizer.cs) is getting pretty byzantine. It operates by defining a massive set of regexes, which are checked in order; however, it's had to develop some nasty warts, like "free text mode" and tokens that can only appear at the start of a line, as well as tokens that can _reset_ the start-of-line state. It's kinda gross.

A better solution would be to have the lexer have different states; states contain a small number of regexes that define the tokens valid within that state. When a token is encountered, it can change the current state.

(This is basically exactly what the ACE syntax highlighter does to determine the token types.)

**Comment by konistehrad** [comment]
Oh bless, I was noodling around with adding [setter link](http://twinery.org/wiki/link#setting_variables_with_setter-links) support and this would be a big help!

**Comment by desplesda** [comment]
If anyone's interested, here's an early build of Yarn Spinner as at bf9cc1f6e7 that contains the new lexer. This is a large change, and there's potential for breakage; I got all the bugs I encountered, so I don't have any new issues to log, but I'd like other eyes to check it out, too.

[YarnSpinner-0.9.8-37-gb9908eb-development-source-minimal.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/201289/YarnSpinner-0.9.8-37-gb9908eb-development-source-minimal.unitypackage.zip)

**Comment by desplesda** [comment]
lolwhoops, that build is from b9908eb, not bf9cc1f.

**Comment by ikofarlight** [comment]
Nice, I'll throw this new build in and test drive it later!

**Comment by desplesda** [comment]
So far, everything's looking good, and I haven't heard any bad news from anyone, so I'm closing this issue. If you have problems with the new lexer, please open a new issue!
