### ISSUE TITLE
Error in DialogueRunner when there are no 'sourceTexts'

### ISSUE THREAD

**Issue by Delament** [thesecretlab/YarnSpinner#41]
I'm adding a DialogueRunner to my game at runtime, and as such, when it hits Start, there aren't any text assets in the sourceText array (they're added later when the NPCs are loaded). The code throws an error when trying to iterate over the array as it's null. I fixed this with a null check before the iteration loop, but I thought I'd point it out here.

A similar thing happens with the switch statement in the example variable storage (the defaultVariables array).

**Comment by desplesda** [comment]
Thanks for the bug report! 

If you've fixed it, would you like to [fork the repo](https://help.github.com/articles/fork-a-repo/), add your changes, and [send a pull request](https://help.github.com/articles/using-pull-requests/)?

**Comment by Delament** [comment]
Done! 
Its very minor, but I thought I'd point it out regardless. Thanks for the great work guys!

**Comment by desplesda** [comment]
(Fixed thanks to #43)
