### ISSUE TITLE
Don't include the $ prefix when communicating with variable storage

### ISSUE THREAD

**Issue by desplesda** [thesecretlab/YarnSpinner#50]
Yarn Spinner prefixes all variable names with $, to aid in parsing. However, when communicating with the variable storage system, this $ is included. This doesn't add anything meaningful, and causes confusion for users who are attempting to set variables outside of Yarn Spinner and forgetting to include the $.

The $ should be either removed, or made optional.

**Comment by bowlercaptain** [comment]
Presumably, Yarn spinner might share a save system with non-yarn variables (for example, Unity's Playerprefs system), and including the $ prefix would prevent collisons. However, it seems like a much less likely use case that an existing project accidentally name-collides with a yarn variable, and much _more_ likely that a developer would want to hand-edit a yarn variable outside yarn.

Accidental collisions could be prevented in other ways, notably by the dev adding their own expected prefix to yarn variable names before storage (I save everything as Yarn[varname]), and/or docs making it clear what the "reserved words" are - variables that the Dialogue Runner will save and retrieve by itself. This may be unnecessary - these variables are named in complex enough ways that collisions are already unlikely.

That's every argument I can think of; I recommend this change be adopted.

**Comment by McJones** [comment]
I don't really understand the advantage to having this done in core, you have to implement your own interface to the variable storage through VariableStorageBehaviour and in there you can have code to add/strip out the $ symbol. I guess I don't really see what advantage there is to changing the working parser for a feature that end users can choose to do on their own.

I think it might be better if the documentation was updated to say something along the lines of "you can do any processing on the name of variables you want". This means that we effectively get this feature for people who want it, without complicating the internals of Yarn Spinner.

**Comment by desplesda** [comment]
I've looked at this a bit too, and I agree with @McJones. We'd either end up filtering and defiltering variable names in `Yarn.VariableStorage` in order to achieve this, and I really don't see that as worth it.

I'll leave this open for now; the next step will be to add documentation that tells users they can make their `Yarn.VariableStorage` as lenient as they like in terms of variable names.

**Comment by McJones** [comment]
This all feels like it should be a part of a larger "Rules For Naming Things In Yarn Spinner" discussion at some point down the track.
