### ISSUE TITLE
Provide Node Tags in Yarn.Line

### ISSUE THREAD

**Issue by TheSabotender** [thesecretlab/YarnSpinner#51]
Currently, the DialogueUIBehaviour's RunLine receives a Yarn.Line argument, that only contains the text the line should display, it would be usefull if Yarn.Line could also contain the node's tags (they are in the json file).

This is usefull for providing the code with a speaker name, portrait ID, speech bubble color, etc. without needing to use a command call

Tags could also be provided in Yarn.Options

**Comment by BrodyB** [comment]
Just started working on a jam game using YarnSpinner, and this is the first thing I've found myself desperately wanting. This would be so incredibly useful.

**Comment by RicardoEPRodrigues** [comment]
Any development on this?

**Comment by arendhil** [comment]
Any update on this? A coworker made this but didn't send a pull request. However, I see that NodeTags were added in the Node object while parsing but it is not exposed in the DialogueRunner. It might be a newbiness of my part. If it is easy to access this data, can someone explain how it should be done? If not I'll adapt the code I have with the implemented structure.

**Comment by RicardoEPRodrigues** [comment]
I made a Pull Request https://github.com/thesecretlab/YarnSpinner/pull/117 with this, but it seems the development has stopped...

**Comment by desplesda** [comment]
Hi! Development has not stopped, I’ve just been extremely busy over the last little while. If anyone wants to help review these PRs and ensure they’re ready for merging, I’d love the assistance!
