### ISSUE TITLE
InvalidCastException when constructing a Value with an integer

### ISSUE THREAD

**Issue by renaudbedard** [thesecretlab/YarnSpinner#52]
When creating a Value like this : 

`var someValue = new Value(1);`

The Value(object) constructor throws an InvalidCastException because the int gets boxed to an object, and then the constructor tries to unbox it as a float.

(Workaround : don't use integers, floats work)

**Comment by desplesda** [comment]
I’ve just pushed a commit to development that includes a fix for this: a2826c62fd

Attached is a Unity package containing the source at this point. Can you try it out and let me know if it solves your problem?

Thanks! :)

**Comment by desplesda** [comment]
Forgot that you can't attach .unitypackages to replies. Haha.

Here's a zip of the same thing.

[YarnSpinner-0.9.9-77-ga2826c6-development-source-minimal.unitypackage.zip](https://github.com/thesecretlab/YarnSpinner/files/431362/YarnSpinner-0.9.9-77-ga2826c6-development-source-minimal.unitypackage.zip)

**Comment by renaudbedard** [comment]
That does work, thanks!
