### ISSUE TITLE
Assigning Source Text Dynamically

### ISSUE THREAD

**Issue by wolfbrother9393** [thesecretlab/YarnSpinner#59]
Hey!

For my Unity project I'm trying to setup the Yarn Spinner integration with the Dialogue Runner and Dialogue UI script to exist as a single interface and pass in new Text Assets into the DialogueRunner.cs's SourceText[] array as they're needed. For example, I have one UI screen that visualizes all of the text and I have different actors in the scene that you walk up to and activate. This replaces the Text Asset in the Source Text array and attempts to run dialogue. 

The issue I'm currently having is that the first text runs fine (though it does so without me seeing a TextAsset being placed in the public SourceText array in the Inspector). Then when I approach another actor, it opens the Dialogue GUI but no text appears.

Would there be a better method to doing this? I think it has something to do with the Yarn.Unity.VariableStorageBehavior and DialogueRunner.cs' line 94 where the JSON files are being loaded in, but I figured there's probably an easier route to doing this than me rewriting some of the implementation.

Thanks for the help!

-Emerson

**Comment by desplesda** [comment]
Hi! (Apologies for taking longer than I expected to get to this!)

If each actor has a different set of nodes that need to be run, it feels like you should give each actor a different node (with a different name) to kick off their dialogue; when you walk up to them, your script should trigger the specified node.

Please let me know if I'm missing something really obvious about your problem, though!

**Comment by wolfbrother9393** [comment]
Hey! Thanks for getting back with me.
Rather than having a huge script with tons of nodes, I'm aiming to make multiple smaller scripts. Does that make sense? The problem I'm running into is that the Yarn Runner is running the previously removed script from the starting node even after I switch files out. Is this something where I need to update the Node as well, even if all of my scripts begin with a node titled "Start"?

**Comment by desplesda** [comment]
You can put multiple script files in the Dialogue runner. As long as they all contain unique node names, it'll work fine. Does that help?

**Comment by wolfbrother9393** [comment]
I'll give that a shot and report back!

**Comment by wolfbrother9393** [comment]
Alright! I have things working now. If you're curious, the way I have it setup is as follows:

I have triggerable game objects in the scene which contain a string to identify the start node I wish to use when that game object is activated. If you're within a certain distance and press the trigger button it sends out a message to my UI system to activate (and enable) the components for Yarn and the Yarn GUI and place them in front of the player character. Then it takes the start node string from the triggerable game object and replaces the DialogueRunner.cs' startNode string and calls the StartDialogue method.

I preload all the scripts I'm going to use in the scene in the SourceText field of the DialogueRunner and it pulls them all from there. I also made a call to my UI Manager in the Dialogue UI which removes the Yarn window and disables it when the script is finished.

**Comment by desplesda** [comment]
Awesome!

In addition to changing the `startNode` variable's value, you can also call `StartDialogue` and pass a node name as a parameter. (When you don't provide a node name to `StartDialogue`, it uses `startNode`.) Hope that's useful to you!

I'll close this issue now, since it seems like your issue is resolved, but if you've got further questions, feel free to re-open or add a new issue.
