### ISSUE TITLE
Inconsistent file naming

### ISSUE THREAD

**Issue by PeteLawler** [thesecretlab/YarnSpinner#62]
As yet, I'm unsure how much of this goes on. As such, I intend this to be a placeholder for inconsistent filenaming as I find it. Preference in file renaming should be given to removing spaces then renaming if needs be.

Documentation/YarnSpinnerLogo.png -> Unity/Assets/Yarn Spinner/Code/Editor/Yarn Spinner Logo.png

**Comment by TheMartianLife** [comment]
Changed. Thanks!
