### ISSUE TITLE
Spaces in filenames are not nice

### ISSUE THREAD

**Issue by PeteLawler** [thesecretlab/YarnSpinner#63]
Manipulation of source files can be problematic when the files have spaces in them. Yes, it can all be worked around with effort. However, it's just easier if spaces are avoided either by using no space or the underscore character.

The following directories contain spaces:
./Unity/Assets/Yarn Spinner
./Unity/Assets/Yarn Spinner/Examples/Demo Scripts
./Unity/Assets/Yarn Spinner/Examples/Demo Assets

The following files contain spaces:

./Unity/Assets/Yarn Spinner/Examples/Yarn Spinner Basic Example.unity
./Unity/Assets/Yarn Spinner/Examples/Yarn Spinner Complex Example.unity
./Unity/Assets/Yarn Spinner/Examples/Demo Scripts.meta
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Localised/Simple Example Script_IT.csv.meta
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Localised/Simple Example Script_IT.csv
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Localised/Simple Example Script_EN.csv.meta
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Localised/Simple Example Script_EN.csv
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Simple Example Script.json.meta
./Unity/Assets/Yarn Spinner/Examples/Demo Assets/Simple Example Script.json

Please note this is not a comprehensive list. I only did a basic check.

**Comment by TheMartianLife** [comment]
Changed. Thanks!
