### ISSUE TITLE
Yarn commands to customize display visuals

### ISSUE THREAD

**Issue by wolfbrother9393** [thesecretlab/YarnSpinner#64]
Is there support for customizing the choice buttons from the yarn script? For example, if I were to have dialogue with a Paragon/Renegade option or a question with the answers represented as pictures, could I put a command in the Yarn script to look up a different button image to make those specific options appear blue/red, or replace the dialogue choice entirely with an image?
Thanks!

**Comment by desplesda** [comment]
The way I'd do it right now would be to put stuff that your game looks for, like:

```
-> This is the paragon choice! #paragon
-> This is the renegade choice! #renegade
```

Then, in your game, search for and remove the tags, and do whatever other stuff you want, like set the colour or image.

(If you do the tags in a #hashtag style, that'll play nicely with some native tag support I'm working on.)

**Comment by wolfbrother9393** [comment]
I don't fully grasp how things that are labeled with the #hashtag are pulled in from Unity.
Do you mean I create different button prefabs within the Frame->Options List and use the unity Tags to tag them whatever the #label is?

**Comment by desplesda** [comment]
Not quite! I'm suggesting that you include something like "#paragon" in the option; when you receive options for Yarn Spinner, you search the option text for "#paragon", and modify the button that that option is presented in.

Something like, in your DialogueUIBehaviour:


````csharp
public override IEnumerator RunOptions (
    Yarn.Options optionsCollection, Yarn.OptionChooser optionChooser)
{

    string option = // one of the options in optionsCollection
    if (option.IndexOf("#paragon") != -1) {
        // change the button to be blue or something
    }
}
````

**Comment by wolfbrother9393** [comment]
Sorry I never came back and told you I got everything working! I had a trip coming up at the time and ended up getting pulled away. 

Anyways, I got it working! I have it so if "#image" is read, it looks immediately after it for the directory where the image I want is stored. So the option ends up looking like this: [[Dune field #image-Yarn Images/Depositional Environment/Dune field|dunefield]]
It also switches the set of option buttons to a separate one I have set up to display in a grid. I recorded a video so you can [see what it looks like in-game](https://drive.google.com/open?id=1Bc_aTnZjJEobYbv1XCU3xKLc_F2u3DtJ-A).

Thank you so much for your help! Consider this issue solved.

**Comment by desplesda** [comment]
Woo, that's awesome! 😁  Thanks for coming back to update the issue, I really appreciate it!
