### ISSUE TITLE
Unity is Loading the Wrong Node on a Button Click

### ISSUE THREAD

**Issue by SamuelJackson1196** [thesecretlab/YarnSpinner#67]
I would like to say that I don't have very much experience in programming, and am probably in over my head here. But, I thought that Yarn and YarnSpinner would be really good tools, so I'm trying to learn them at the same time as basic Unity scripting. Having said that, here's my bug report:

## ***Software Versions***
Unity---------5.4.1
Yarn----------0.2.1
YarnSpinner-0.9.9

## ***The Problem***
I am trying to get Unity to play a simple dialogue (almost a carbon copy of the Basic Example Dialogue that's included with the YarnSpinner package). However, I'm having an issue with how the nodes are loading when I click a button in the game, and it doesn't bring up any errors in the console for me to go by.

The problem is that **no matter what button I click, I always get taken to node linked to by the first option**. This happens no matter what node I'm in. For example:

My first node is "TableofContents". It has 6 options, linked to (and displayed on screen) in this order:

1. Lines
2. Options
3. Shortcut Options
4. Variables
5. If Statements
6. Functions

All six of those buttons are displayed in the game view, and they are all clickable. However, regardless of what button I click, I always get taken to the "Lines" node (as though I had clicked the Lines button, even if I hadn't).

This problem persists throughout the entire dialogue (in the "Options" node, I have two buttons that link to "ShortcutOptions" (first) and "Variables" (second), no matter which one I click, I get immediately taken to the "ShortcutOptions" node).

Like I said earlier, this dialogue is almost a carbon copy of the Basic Example Dialogue. With that said, I thought that maybe I had changed something that I shouldn't have.

## ***Differences Between My Dialogue and the Basic Example***
1. Automatic Commands is unchecked in my Dialogue Runner (Script) component of my Dialogue object.
After checking (and unchecking) it a few times, I concluded that it wasn't affecting anything within my game.

2. In the Example Dialogue UI (Script) component of the same object, my Dialogue Container is set to be the DialogueContainer object.
Aside from the name, the DialogueContainer object is completely identical to the Frame object in the example. Changing the name to Frame had no affect.

3. My Text Speed is set to 0.
Changing this to match the example dialogue had no affect other than driving me insane with how slow it was.

4. I have 6 option buttons instead of 3.
Reducing the number of buttons causes an error (due to me having a node that offers 6 choices). All of the buttons are set to their correct elements (Option0 is set to Element 0), and changing the buttons' numbers to start at 1 (like in the example script) did nothing.

5. In the Example Variable Storage (Script) component of the same object, my Default Variables have a size of 0.
The basic example has a size of 2 (with act and day being its variables). My dialogue does contain one variable (review), but changing the size to 1 and adding it in doesn't affect anything at all.

## ***Scripts***
I'm only using three scripts. They're all included with the YarnSpinner package, and are completely unchanged:

1. DialogueRunner.cs
2. ExampleDialogueUI.cs
3. ExampleVariableStorage.cs

## ***Restarting***
Thinking that I may have made some simple error early on, I opened up a new project in Unity and in Yarn. After redoing the entire project over again, I still ran into the same problem.

## ***What I Think is a Possible Solution (and Am Too Unskilled/Inexperienced to do)***
In the scripts (probably ExampleDialogueUI.cs) it might be possible to edit how the code reads the buttons. Something along the lines of:

1. Identifying the text on them.
In the editor they all say "Option0", "Option1", etc. In the game however, they say things like "Lines" or "ShortcutOptions". Would it be possible to change the code so that it reads the string displaying on the buttons (Lines/ShortcutOptions). 

2. Loading the next node based on the string that was identified from the above.
Like reading that the button says "ShortcutOptions", converting that into a string called ShortcutOptions, and then loading a node that has a name the same as that string.

## ***Final Words***
Thanks to anyone who actually read this entire thing (I'm sorry it was so long).

Any help at all would be greatly appreciated.

Thanks again.

**Comment by desplesda** [comment]
Hi! Thanks for your very comprehensive issue report.

Can you check your buttons, and make sure that they're calling your ExampleDialogueUI object's "SetOption" function (you can find it in the button's OnClick section in the Inspector)? The first one should be set up to call the function and pass the number 0, the second number 1, and so on.

**Comment by SamuelJackson1196** [comment]
That was it!

I knew it was something completely obvious!

All of the buttons were set to pass 0, instead of their own number.

Thanks for the quick response man, that was exactly what I needed.
