### ISSUE TITLE
Deploy Release and Nightlies via Travis

### ISSUE THREAD

**Issue by PeteLawler** [thesecretlab/YarnSpinner#82]
Need to have travis send back to GH, thus making available, nightly builds and releases.

Releases can be handled via Travis's Release uploading https://docs.travis-ci.com/user/deployment/releases/

Nightlies probably need handling via Travis's cron functionality, that is currently in beta. This is because Travis doesn't support uploading branches, it only supports releases.

**Comment by PeteLawler** [comment]
My bad, cron isn't what to use for Nightly. Using a custom script at each build to push the resultant back, similar to how the Pages are pushed https://docs.travis-ci.com/user/deployment/script

**Comment by PeteLawler** [comment]
Releases should now be auto-deployed when the tag is created. However, it'd appear that this automatically creates a release information file of the changes, with no way to edit the contents. That's to say, one can't easily customise a release file (eg, RELEASE.MD) without having to fiddle with command line options and the API directly (by editing some Markdown, grabbing the changelog entries since the previous tag, creating the new tag then pushing this through GitHub as a Release). Standard git would permit this with annotated tagging, however from my current reading there's no way to do it on GitHub.

**Comment by TheMartianLife** [comment]
We have decided that the current state of the project does not require this level of support,  will keep in mind for when the project gets larger. Manually generating release artefacts is fine for the moment, but we will return to this sometime.
