### ISSUE TITLE
Example project needs updating to new .yarn.txt format

### ISSUE THREAD

**Issue by PeteLawler** [thesecretlab/YarnSpinner#84]
While tightening the documentation for authors on on how to write Yarn, I thought it'd be best if I could convert the .json files to the new .yarn.txt format as examples.
After discussion with Jon, I did this and remove the .json files. However, the example projects need updating so as to point to these new files.

Files removed:
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Simple Example Script.json
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Simple Example Script.json.meta
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Sally.json
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Sally.json.meta
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Ship.json
 Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Ship.json.meta
 
Files created:
Unity/Assets/Yarn Spinner/Examples/Demo Assets/Simple Example Script.yarn.txt
Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Sally.yarn.txt
Unity/Assets/Yarn Spinner/Examples/Demo Assets/Space/Ship.yarn.txt

This file change went in as https://github.com/thesecretlab/YarnSpinner/commit/9167641569330cfa2e0881d0e924275239205292

**Comment by rcuddy** [comment]
Am I right in reading this issue and https://github.com/thesecretlab/YarnSpinner/issues/81 json on consoles that YarnSpinner is moving away from json support at all, which would also make the NewtonSoft includes in the Unity project obsolete?

**Comment by PeteLawler** [comment]
I believe this is one of @desplesda's aims with this planned change from JSON is to have reflection not break under NewtonSoft, yes,

**Comment by PeteLawler** [comment]
Examples in Development updated accordingly

**Comment by PeteLawler** [comment]
Accidentally closed

**Comment by PeteLawler** [comment]
Fixed in 9e4a7caabdae72ba4e294d4dbe916407693937ff
