### ISSUE TITLE
unity demo is broken

### ISSUE THREAD

**Issue by nowakf** [thesecretlab/YarnSpinner#99]
-or at least, I can't get it to work. It spits out a load of errors like:

"Assets/YarnSpinner/Code/DialogueRunner.cs(461,74): error CS0234: The type or namespace name `VariableStorage' does not exist in the namespace `Yarn'. Are you missing an assembly reference?"

Any hints?

**Comment by desplesda** [comment]
If you've just cloned the repo and opened the Unity project, the built DLLs that contain the Yarn Spinner classes won't be present, and you'll get that error. Grab the built package from the project's releases page, and install that package, and it should work. 

I'll close this issue now, but if you're still seeing problems, please don't hesitate to re-open it!

**Comment by nowakf** [comment]
Sadly - no - I downloaded the built DLL. Cloning the repo gives a different error. The classes that aren't present are:
VariableStorage
Dialogue
Line
Options
OptionsChooser
Command
and Value

Gonna try dl'ing an older build, see if that works.

**Comment by nowakf** [comment]
9.9 works just fine.

**Comment by molocai** [comment]
Same problem here.

**Comment by johnomahen79** [comment]
So I do not find a unity package to import...did i miss that in the clone?
